spring:
  datasource:
    username: root
    password: root
    # userUnicode:保证不乱码  characterEncoding:设置字符集 serverTimezone:设置时区
    url: jdbc:mysql://localhost:3306/test?userUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 指定连接池
    type: com.alibaba.druid.pool.DruidDataSource

    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    # 初始化大小
    initialSize: 5
    # 最小值
    minIdle: 5
    # 最大值
    maxActive: 21
    # 最大等待时间,配置获取连接等待超时,时间单位是毫秒数ms
    maxWait: 60000
    # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在连接池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,log4j
    # 最大PSCache连接
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
# 整合mybatis
mybatis:
  # 别名
  type-aliases-package: com.example.pojo
  # mapper地址  这里是以/分隔 表示这是文件夹分隔
  mapper-locations: classpath:mybatis/mapper/*.xml
